### ISSUE TITLE
When we evaluate the performance of LRA on testing datasets, the returnning rsults of the function "ddim_sample_step" in moel_diffusion.py is y_t_m_1

### ISSUE THREAD

**Issue by LanXiaoPang613** [puar-playground/LRA-diffusion#2]
When performing LRA on testing datasets,  why does the function "ddim_sample_step" in moel_diffusion.py return y_t_m_1 instead of y_0_reparam? Actually, in the CARD, the output prediction is y_0_reparam, which is depicted in the algorithm 2 of CARD. Looking forward your reply, thank for your attention.

**Comment by zhaihaotian** [comment]
But in the source code of CARD , you can see the CARD use the y_t_m_1 as the same
